version: '3.8'

services:
  # Base de Datos (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: santana_db_local
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: pablo123
      POSTGRES_DB: fac_pablo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - santana_network
    restart: always

  # Backend (NestJS API)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: santana_api_local
    environment:
      DATABASE_URL: postgresql://pablo:pablo123@db:5432/fac_pablo_db?schema=public
      JWT_SECRET: mi_secreto_super_seguro_12345
      JWT_EXPIRES_IN: "1h"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - santana_network
    restart: always

  # Frontend (Vite React App)
  web:
    build:
      context: ./frontend
    container_name: santana_web_local
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - santana_network
    restart: always

networks:
  santana_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
